# Generated by Django 3.2.9 on 2021-11-29 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidades', models.IntegerField(choices=[(1, 'Informática'), (2, 'Eletromecânica'), (3, 'Edificações')])),
            ],
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=150)),
                ('resumo', models.TextField()),
                ('palavras_chave', models.CharField(max_length=250)),
                ('ano_documento', models.IntegerField()),
                ('local_estagio', models.CharField(max_length=150)),
                ('arquivo', models.FileField(upload_to='pdf/')),
                ('autor', models.ManyToManyField(to='cadastros.Autor')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.curso')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.orientador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
